### ISSUE TITLE
UTF Character handling issue?

### ISSUE THREAD

**Issue by giray** [HolgerHees/cloudsync#11]
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/giray/Documents/Docs/XX/Yyyyy/Abn Abedeo??lu_files
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.io.File.toPath(File.java:2234)
	at cloudsync.connector.LocalFilesystemConnector.getItem(LocalFilesystemConnector.java:442)
	at cloudsync.helper.Handler.backup(Handler.java:459)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:428)
	at cloudsync.Cloudsync.start(Cloudsync.java:108)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)
giray@wasp:~/bin/cloudsync$

**Comment by HolgerHees** [comment]
Can you send me a testfile with that characters.

**Comment by giray** [comment]
iray@wasp:~/Pictures$ mkdir /data/TEST
giray@wasp:~/Pictures$ cd /data/TEST/
giray@wasp:/data/TEST$ cp /etc/services abçdefgğiıöüşŞİĞÇ.txt
giray@wasp:/data/TEST$ cd ~/bin/cloudsync/
giray@wasp:~/bin/cloudsync$ ./cloudsync.sh --name "Wasp.Test" --backup
/data/TEST
[2015.03.03 19:47:43] - FINEST - use exclude pattern: [^.*\.git/.*$] |
[$.*\.svn/.*$]
[2015.03.03 19:47:44] - INFO - load structure from remote server
[2015.03.03 19:47:44] - INFO - refreshed client token stored in
'/home/giray/bin/cloudsync/.cloudsync.token'
Exception in thread "main" java.nio.file.InvalidPathException: Malformed
input or input contains unmappable characters:
/data/TEST/ab??defg??i????????????????.txt
at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
at java.io.File.toPath(File.java:2234)
at
cloudsync.connector.LocalFilesystemConnector.getItem(LocalFilesystemConnector.java:442)
at cloudsync.helper.Handler.backup(Handler.java:459)
at cloudsync.helper.Handler.backup(Handler.java:428)
at cloudsync.Cloudsync.start(Cloudsync.java:108)
at cloudsync.Cloudsync.main(Cloudsync.java:139)

**Comment by HolgerHees** [comment]
The problem is related to the local $LANG setting. I set it to de_DE.UTF-8 which is wrong in your case. On my filesystem your testfilename is working fine. Anyway, I send you a new shellscript to your mailaddress for testing, which only set the $LANG variable to "en_US.UTF-8" if no other $LANG variable is defined. That means your local $LANG is not overwritten anymore.
