### ISSUE TITLE
Network hickup causes exception

### ISSUE THREAD

**Issue by giray** [HolgerHees/cloudsync#13]
Hi ... 

  seems like a timeout ... nothing major, but maybe nice to handle the exception with a nicer
message, or add a retry loop.  Especially nice for laptops etc, that can continue to backup
after switching locations.

-------------------------------
[2015.03.04 21:40:23] - FINE - create file 'Backup/Docs backup 20021107/unix/1.0userlevel-linux/self_study.doc'
[2015.03.04 21:41:03] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 1/6
[2015.03.04 21:41:13] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 2/6
[2015.03.04 21:41:13] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 3/6
[2015.03.04 21:41:33] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 4/6
[2015.03.04 21:41:43] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 5/6
[2015.03.04 21:42:03] - WARNING - ioexception: 'www.googleapis.com' - remote search - retry 6/6
[2015.03.04 21:42:03] - INFO - error: Unexpected error during remote search of folder 'Backup/Docs backup 20021107/unix/1.0userlevel-linux'

cloudsync.exceptions.CloudsyncException: Unexpected error during remote search of folder 'Backup/Docs backup 20021107/unix/1.0userlevel-linux'
	at cloudsync.connector.RemoteGoogleDriveConnector.validateException(RemoteGoogleDriveConnector.java:677)
	at cloudsync.connector.RemoteGoogleDriveConnector._searchDriveItem(RemoteGoogleDriveConnector.java:506)
	at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:201)
	at cloudsync.helper.Handler.backup(Handler.java:471)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:428)
	at cloudsync.Cloudsync.start(Cloudsync.java:108)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)
Caused by: java.net.UnknownHostException: www.googleapis.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at cloudsync.connector.RemoteGoogleDriveConnector._searchDriveItem(RemoteGoogleDriveConnector.java:503)
	... 9 more
giray@wasp:~/bin/cloudsync$

**Comment by HolgerHees** [comment]
Currently I already tried 6 retries, but cancelled it to avoid endless loops.

What I can do is:

- hide the stack trace for HostNotFoundExceptions
- for all other IOExceptions it will work like before
- provide a command line argument "-ask-to-continue" which will show you a Y/n question to cancel or start next 6 retries.

Additional I will add/rename the following parameters in my next version.

-dry-run
-progress
-existing update/ignore
-retries number
-waitretry seconds
-ask-to-continue

**Comment by giray** [comment]
sounds good

**Comment by HolgerHees** [comment]
fixed with commit b072538570c0c3cf76583672316ee21267d11f43
