### ISSUE TITLE
NullPointerException on start

### ISSUE THREAD

**Issue by gelse** [HolgerHees/cloudsync#22]
Call:
```
./cloudsync.sh --backup /home/werner/testBackupDir --name testbackup
```
Log:
```
[2015.10.21 13:53:08] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.10.21 13:53:16] - INFO - load structure from remote server
```
Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
        at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
        at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
        at com.google.api.client.json.jackson2.JacksonFactory.createJsonParser(JacksonFactory.java:92)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:85)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:88)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:384)
        at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
        at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
        at cloudsync.connector.RemoteGoogleDriveConnector._getDriveFolder(RemoteGoogleDriveConnector.java:706)
        at cloudsync.connector.RemoteGoogleDriveConnector._getBackupFolder(RemoteGoogleDriveConnector.java:696)
        at cloudsync.connector.RemoteGoogleDriveConnector.initService(RemoteGoogleDriveConnector.java:894)
        at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:401)
        at cloudsync.helper.Handler.readRemoteStructure(Handler.java:260)
        at cloudsync.helper.Handler.readRemoteStructure(Handler.java:254)
        at cloudsync.helper.Handler.init(Handler.java:140)
        at cloudsync.Cloudsync.start(Cloudsync.java:120)
        at cloudsync.Cloudsync.main(Cloudsync.java:160)

```

Happens in both authentication options the same way (when using installed application i have to get and enter the code first).

Running on a raspberry pi, java 7 JDK:
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb7u1+rpi1)
OpenJDK Zero VM (build 24.79-b02, mixed mode)
And Maven 3.3.3 and ofc the JCE installed.

Tbh, i have no idea where to start here.

On a sidenote: it should not have to do with my (headless) raspi, as gsync (https://github.com/iwonbigbro/gsync) is working fine. I just need crypto, too.

**Comment by HolgerHees** [comment]
have you checked

https://github.com/HolgerHees/cloudsync/wiki/Google-Drive-API

and

https://github.com/HolgerHees/cloudsync/wiki/Google-Client-Credentials

**Comment by gelse** [comment]
of course. The GUI does look a bit different now, but basically the controls are the same - and i created (for testing) both.
But with both auth options i have a potential error source:
- Installed Application: i have a headless raspi, so i had to copy/paste the provided link, opened it in a browser on a different computer and copy/pasted the given key back. When i tried other solutions for google sync i somewhere stumbled upon the statement that this only works when the client and the browser are on the same computer. I am unsure if i should believe this, but just fyi.
- Service Account:
Somehow i was not able to log into my admin-console as mentioned here: https://developers.google.com/drive/web/delegation#delegate_domain-wide_authority_to_your_service_account - i think the reason is that my google account is a customer account.

**Comment by gelse** [comment]
Update:
when authing via Installed Application, the stacktrace is:
```
Exception in thread "main" java.lang.NullPointerException
        at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
        at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
        at com.google.api.client.json.jackson2.JacksonFactory.createJsonParser(JacksonFactory.java:92)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:85)
        at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:88)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)
        at cloudsync.connector.RemoteGoogleDriveConnector.init(RemoteGoogleDriveConnector.java:163)
        at cloudsync.Cloudsync.start(Cloudsync.java:102)
        at cloudsync.Cloudsync.main(Cloudsync.java:160)
```

**Comment by HolgerHees** [comment]
the "customer account" can be the reason. Because the error shoes you that some configuration on the google side is preventing you from using this service.

**Comment by gelse** [comment]
That explains, why auth via Service Account fails, but not why it fails with Installed Application.

**Comment by HolgerHees** [comment]
can you recheck it with a personal account.

**Comment by gelse** [comment]
I think we have some misunderstanding here. What i call "customer-account" is just the normal personal account. The same account i am using for development a.s.o.

But i did some further testing and registered a domain to get access to the admin-console. There i followed the steps to authorize the client for google drive as mentioned in https://developers.google.com/drive/web/delegation#delegate_domain-wide_authority_to_your_service_account

Did have no effect, same exception as before.

One particular question:
Is it correct, that for using the service account you have to create a google apps for work account? The one where you have to pay monthly?

**Comment by HolgerHees** [comment]
I don"t know it exactly. But for the installed app account there is no need for an app for work account.

I use it with my own private google account.

**Comment by gelse** [comment]
Let me guess - you are syncing from the same machine as where you accepted the app in the browser?

If my theory about the need of having the installed app authentication (with the url you get provided from cloudsync) on the same machine as the app is correct, that should be reproduceable with a fresh google-account and a headless client.

Could someone test this please?

**Comment by HolgerHees** [comment]
The procedure is.

- Start the application.
- copy the URL and open it with a browser
- confirm the application
- copy the token from the input field of the confirmation window
- paste it to the command line where your application is currently running
and waiting for your input
- now the application is fetching an access token with your pasted token
- those access token is stored in a tmp file on the computer where your
application is running.
Am 21.10.2015 6:06 nachm. schrieb "Werner Schiller" <
notifications@github.com>:

**Comment by gelse** [comment]
That is exactly what i did.
But propably the storing in the tmp file does not work on my machine - i will check that and report back later. Thanks for the support up to now.

**Comment by gelse** [comment]
I checked the code. As it seems, the storing in the access token never happens.
```java
final String code = new BufferedReader(new InputStreamReader(System.in)).readLine().trim();
					
clientToken = flow.newTokenRequest(code).setRedirectUri(REDIRECT_URL).execute();
					
storeClientToken(jsonFactory);
LOGGER.log(Level.INFO, "client token stored in '" + this.clientTokenPath + "'");
```

That log INFO never happens. Imo that means the token never gets stored. Which means the authentication propably is failing, which gives additional reason to believe that my assumption that one has to confirm the application on the SAME MACHINE as the application runs.

**Comment by HolgerHees** [comment]
that is not needed. I confirmed the application on my notebook and the application itself is running on my headless server.

**Comment by gelse** [comment]
As it seems, the error was quite simple. I somehow managed to put the client ID in the config in the secret field... silly me.

It's working now.

**Comment by HolgerHees** [comment]
:-) it happens

**Comment by gelse** [comment]
If i manage to get some time on the weekend, i will try to make some input checkings for those values, f.e. the client secret cannot have an @ inside and propably is 24 characters long... Such things.

At least this project propably will be the reason for me to install some java IDE again. ;-)

**Comment by gelse** [comment]
On a sidenote - what does the --progress flag do? i do not see any difference between with and without?

**Comment by HolgerHees** [comment]
the progress flag showes you a progress message for huge files

2015-10-22 9:14 GMT+02:00 Werner Schiller <notifications@github.com>:
