### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by gelse** [HolgerHees/cloudsync#26]
Encryption/Compression should theoretically be able to use streams directly, instead of copying binaries/use memorystreams as the stacktrace shows below. That would reduce the memory usage drastically and also enables to upload AND encrypt simultanously (the latter should be configurable).

Refactoring for separation of concerns is a prerequisite for that (and already started in the fork from gelse).

Exception for reference:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at java.io.OutputStream.write(OutputStream.java:75)
        at javax.crypto.CipherOutputStream.write(CipherOutputStream.java:160)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at cloudsync.helper.Crypt._encryptData(Crypt.java:238)
        at cloudsync.helper.Crypt.encryptedBinary(Crypt.java:155)
        at cloudsync.helper.Handler.getLocalProcessedBinary(Handler.java:633)
        at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:512)
        at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:213)
        at cloudsync.helper.Handler.backup(Handler.java:517)
        at cloudsync.helper.Handler.backup(Handler.java:585)
        at cloudsync.helper.Handler.backup(Handler.java:585)
        at cloudsync.helper.Handler.backup(Handler.java:471)
        at cloudsync.Cloudsync.start(Cloudsync.java:125)
        at cloudsync.Cloudsync.main(Cloudsync.java:160)
```

**Comment by HolgerHees** [comment]
we should think about a merge of our fork

**Comment by gelse** [comment]
Feel free to do whatever you want - sorry that a lack of time prevented and still prevents me from further developing the refactoring here. What i remember is that it is only halfway finished, as it was not easy to get rid of certain dependencies in both directions. IIRC: Currently my fork still uses lot of the old structure; I tried to make it as readable as possible, but it's too long ago to remember the details.
My next free timeslot is the weekend 18th/19th - i can try to take a look and finish what i have started. 

But - my fear is that a merge will not be easy then, as it already is a major refactoring in structure. I remember i failed in a quick try to merge your changes into my fork last time...

**Comment by HolgerHees** [comment]
and in the meantime my code changed a lot too :-)

**Comment by gelse** [comment]
Propably it's better if a start from scratch then. Except that "continue on error" part.
