### ISSUE TITLE
min_tmp_file_size flag from command line not working

### ISSUE THREAD

**Issue by gelse** [HolgerHees/cloudsync#27]
I have a file with size 131807232 and added the flag
``` 
--min_tmp_file_size 67108864
```
got exception
```
[2015.11.05 09:54:56] - FINE - create file 'AAA/BBB/CCC.avi'
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at java.io.OutputStream.write(OutputStream.java:75)
        at javax.crypto.CipherOutputStream.write(CipherOutputStream.java:160)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at cloudsync.crypt.Crypt._encryptData(Crypt.java:237)
        at cloudsync.crypt.Crypt.encryptedBinary(Crypt.java:154)
        at cloudsync.crypt.CryptProvider.encryptedBinary(CryptProvider.java:35)
        at cloudsync.connector.RemoteGoogleDriveConnector.getLocalProcessedBinary(RemoteGoogleDriveConnector.java:520)
        at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:532)
        at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:214)
        at cloudsync.handler.Handler.backup(Handler.java:517)
        at cloudsync.handler.Handler.backup(Handler.java:585)
        at cloudsync.handler.Handler.backup(Handler.java:585)
        at cloudsync.handler.Handler.backup(Handler.java:471)
        at cloudsync.CloudSyncWorker.Run(CloudSyncWorker.java:40)
        at cloudsync.Cloudsync.start(Cloudsync.java:64)
        at cloudsync.Cloudsync.main(Cloudsync.java:168)
```

Current branch: master from gelse, so an additional source for the error could be a failed merge.

**Comment by gelse** [comment]
additional info: after adding a logging line in Crypt.java and calling with  --min_tmp_file_size 33554432
```
[2015.11.05 10:44:39] - FINE - File size is 131807232 which is lower than 134217728, so crypt in memory.
```
