### ISSUE TITLE
Uncaught Exception: Can't read data : 	at cloudsync.connector.LocalFilesystemConnector.getFileBinary

### ISSUE THREAD

**Issue by giray** [HolgerHees/cloudsync#29]
Hi Holger, 

   I've started using Sophos AV, which block's access to malicious files.  However cloudsync
crashes because it cannot read the file.  Although from an integrity point of view (broken disk, hence potential file corruption) I could understand the backup stopping, my expected behavior would be to log the issue and continue with the backup.

Greetings

Giray

----
2015.12.04 09:34:05] - FINE - create file 'Security/Malware/bill.doc'
[2015.12.04 09:34:05] - WARNING - Can't read data of '/home/giray/Documents/Security/Malware/bill.doc'

cloudsync.exceptions.CloudsyncException: Can't read data of '/home/giray/Documents/Security/Malware/bill.doc'
	at cloudsync.connector.LocalFilesystemConnector.getFileBinary(LocalFilesystemConnector.java:756)
	at cloudsync.helper.Handler.getLocalProcessedBinary(Handler.java:631)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:511)
	at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:212)
	at cloudsync.helper.Handler.backup(Handler.java:517)
	at cloudsync.helper.Handler.backup(Handler.java:585)
	at cloudsync.helper.Handler.backup(Handler.java:585)
	at cloudsync.helper.Handler.backup(Handler.java:471)
	at cloudsync.Cloudsync.start(Cloudsync.java:125)
	at cloudsync.Cloudsync.main(Cloudsync.java:160)
Caused by: java.nio.file.FileSystemException: /home/giray/Documents/Security/Malware/bill.doc: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at cloudsync.connector.LocalFilesystemConnector.getFileBinary(LocalFilesystemConnector.java:746)
	... 9 more

**Comment by HolgerHees** [comment]
can you recheck it?

**Comment by HolgerHees** [comment]
the command line parameter is "--file-error"
