### ISSUE TITLE
Forcing a cache file rebuild

### ISSUE THREAD

**Issue by DigiAngel** [HolgerHees/cloudsync#30]
So I started getting this a couple days ago:
~~~
./cloudsync.sh: 10: ./cloudsync.sh: cannot open 1.7: No such file
./cloudsync.sh: 10: ./cloudsync.sh: [[: not found
[2015.12.22 05:01:14] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.12.22 05:01:15] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.12.22 05:01:15] - INFO - load structure from remote server
[2015.12.22 05:01:16] - INFO - refreshed client token stored in '/opt/cloudsync/.cloudsync.token'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareBackupItem(RemoteGoogleDriveConnector.java:465)
	at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:338)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:228)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:221)
	at cloudsync.helper.Handler.init(Handler.java:123)
	at cloudsync.Cloudsync.start(Cloudsync.java:104)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)
~~~

I've tried -c /path -n name, but I still get this response.  Not sure what I need to take a look at...thank you.

**Comment by HolgerHees** [comment]
Can you update to the latest version. Currently it is "cloudsync-v1.0-beta12"

**Comment by DigiAngel** [comment]
Just did a git pull...here's the results:
~~~
[2015.12.22 13:24:25] - INFO - "en_US.UTF-8" environment detected and used for local filename encoding
[2015.12.22 13:24:34] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.12.22 13:24:38] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.12.22 13:24:38] - INFO - load structure from remote server
[2015.12.22 13:24:39] - INFO - refreshed client token stored in '/opt/cloudsync/.cloudsync.token'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
        at java.util.ArrayList.add(ArrayList.java:473)
        at cloudsync.connector.RemoteGoogleDriveConnector._prepareBackupItem(RemoteGoogleDriveConnector.java:465)
        at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:338)
        at cloudsync.helper.Handler.readRemoteStructure(Handler.java:228)
        at cloudsync.helper.Handler.readRemoteStructure(Handler.java:221)
        at cloudsync.helper.Handler.init(Handler.java:123)
        at cloudsync.Cloudsync.start(Cloudsync.java:104)
        at cloudsync.Cloudsync.main(Cloudsync.java:139)
~~~

Java version:
~~~
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) Server VM (build 25.66-b17, mixed mode)
~~~

Thank you.

**Comment by HolgerHees** [comment]
That is strange. The Source line number in the stacktrace does not exists in the latest release. 

can you check the "version" tag inside your pom.xml

**Comment by DigiAngel** [comment]
On Wed, 2015-12-23 at 01:00 -0800, Holger Hees wrote:

> That is strange. The Source line number in the stacktrace does not
> exists in the latest release. 
> 
> can you check the "version" tag inside your pom.xml
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 
> 

Here it is:

grep version pom.xml 
	<version>v1.0-beta13</version>
			<version>1.2</version>
			<version>1.9</version>
			<version>1.0</version>
			<version>2.4</version>
			<version>3.3.2</version>
			<version>1.51</version>
			<version>1.51</version>
			<version>v2-rev190-1.20.0</version>
			<version>1.20.0</version>
			<version>1.20.0</version>
			<version>[1.7,1.8)</version>
				<version>3.1</version>
				<version>2.3</version>
				<version>2.4.1</version>
				<version>2.8</version>

Thank you.

**Comment by HolgerHees** [comment]
Can you check your lib folder inside the cloudsync directory. Maybe there
is more than one jar file from cloudsync.
Am 23.12.2015 12:48 nachm. schrieb "DigiAngel" <notifications@github.com>:

**Comment by DigiAngel** [comment]
Here's the list:

/opt/cloudsync/lib$] ls -l
total 7704
-rw-r--r-- 1 jlay jlay  255692 Dec 30  2014 bcpg-jdk15on-1.51.jar
-rw-r--r-- 1 jlay jlay 2842667 Dec 30  2014 bcprov-jdk15on-1.51.jar
-rw-r--r-- 1 jlay jlay   81278 Dec 30  2014 cloudsync-v1.0-beta4.jar
-rw-r--r-- 1 jlay jlay   41123 Dec 30  2014 commons-cli-1.2.jar
-rw-r--r-- 1 jlay jlay  263965 Dec 30  2014 commons-codec-1.9.jar
-rw-r--r-- 1 jlay jlay   34827 Dec 30  2014 commons-csv-1.0.jar
-rw-r--r-- 1 jlay jlay  185140 Dec 30  2014 commons-io-2.4.jar
-rw-r--r-- 1 jlay jlay  412739 Dec 30  2014 commons-lang3-3.3.2.jar
-rw-r--r-- 1 jlay jlay   60686 Dec 30  2014 commons-logging-1.1.1.jar
-rw-r--r-- 1 jlay jlay  202382 Dec 30  2014 dropbox-core-sdk-1.7.7.jar
-rw-r--r-- 1 jlay jlay  189191 Dec 30  2014 google-api-client-1.19.0.jar
-rw-r--r-- 1 jlay jlay    2656 Dec 30  2014
google-api-client-gson-1.19.0.jar
-rw-r--r-- 1 jlay jlay  154531 Dec 30  2014
google-api-services-drive-v2-rev139-1.19.0.jar
-rw-r--r-- 1 jlay jlay  271400 Dec 30  2014
google-http-client-1.19.0.jar
-rw-r--r-- 1 jlay jlay    8549 Dec 30  2014
google-http-client-gson-1.19.0.jar
-rw-r--r-- 1 jlay jlay    6720 Dec 30  2014
google-http-client-jackson2-1.19.0.jar
-rw-r--r-- 1 jlay jlay   61084 Dec 30  2014
google-oauth-client-1.19.0.jar
-rw-r--r-- 1 jlay jlay  180110 Dec 30  2014 gson-2.1.jar
-rw-r--r-- 1 jlay jlay 1791384 Dec 30  2014 guava-jdk5-13.0.jar
-rw-r--r-- 1 jlay jlay  291037 Dec 30  2014 httpclient-4.0.1.jar
-rw-r--r-- 1 jlay jlay  172888 Dec 30  2014 httpcore-4.0.1.jar
-rw-r--r-- 1 jlay jlay  223906 Dec 30  2014 jackson-core-2.4.0-rc3.jar
-rw-r--r-- 1 jlay jlay   33015 Dec 30  2014 jsr305-1.3.9.jar

I can just download a fresh tarbzll and copy the config and token over
if that will make it easier.  Thank you.

**Comment by HolgerHees** [comment]
Please remove the beta4 jar file and recompile everything with maven.

**Comment by DigiAngel** [comment]
Ah..yea this isn't compiled...this was from the tarball.  I'll snag the
latest tarball and try again....let you know how it goes thank you.

**Comment by DigiAngel** [comment]
Yea that totally worked:
~~~
[2015.12.23 06:48:37] - INFO - "en_US.UTF-8" environment detected and used for local filename encoding
[2015.12.23 06:48:38] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.12.23 06:48:40] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.12.23 06:48:40] - INFO - load structure from remote server
[2015.12.23 06:48:41] - INFO - refreshed client token stored in '/opt/cloudsync/.cloudsync.token'
[2015.12.23 06:55:08] - INFO - found 1069 folder and 11538 files
[2015.12.23 06:55:08] - INFO - write structure to cache file
[2015.12.23 06:55:09] - INFO - runtime: 390.566 seconds
~~~

Thanks Holger....next time I'll make sure I'm on the latest before I open github tickets :)  Merry Christmas!
