### ISSUE TITLE
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?>

### ISSUE THREAD

**Issue by JohnWang1023** [HolgerHees/cloudsync#32]
[2016.02.20 20:09:08] - INFO - found 18 folder, 259 files and 1 duplicate
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?>
at index 40: E:\music\[140521] TVアニメ「ノーゲーム?ノーライフ」EDテ
ーマ「オラシオン」／白(CV.茅野愛衣) (FLAC+BK)
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at cloudsync.connector.LocalFilesystemConnector.prepareUpload(LocalFiles
ystemConnector.java:126)
        at cloudsync.helper.Handler.clean(Handler.java:398)
        at cloudsync.Cloudsync.start(Cloudsync.java:135)
        at cloudsync.Cloudsync.main(Cloudsync.java:161)

**Comment by HolgerHees** [comment]
I looks like a wrong character set.

What is the first log message.

for me it is

[2016.05.31 13:43:28] - INFO - "de_DE.UTF-8" environment detected and used for local filename encoding

for you it should be a characterset which supports your characters

**Comment by 13reds** [comment]
啊吧啊吧

**Comment by 13reds** [comment]
空泥吉瓦
