### ISSUE TITLE
NullPointerException at cloudsync.helper.Handler.readCSVStructure(Handler.java:242)

### ISSUE THREAD

**Issue by giray** [HolgerHees/cloudsync#33]
Hi, 

  Running cloudsync-v1.0-beta12  I did a backup, then to make sure reran it again and got 
the error.  

```
[2016.03.30 15:47:15] - INFO - write structure to cache file
[2016.03.30 15:47:16] - INFO - total items: 27771
[2016.03.30 15:47:16] - INFO - created items: 1350
[2016.03.30 15:47:16] - INFO - updated items: 50
[2016.03.30 15:47:16] - INFO - removed items: 65
[2016.03.30 15:47:16] - INFO - skipped items: 26371
[2016.03.30 15:47:16] - INFO - runtime: 1173.176 seconds
giray@wasp:~/bin/cloudsync$ ./cloudsync.sh --name "Documents" --backup /Documents/
[2016.03.30 20:26:45] - INFO - "en_US.UTF-8" environment detected and used for local filename encoding
[2016.03.30 20:26:46] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2016.03.30 20:26:46] - INFO - load structure from cache file
Exception in thread "main" java.lang.NullPointerException
	at cloudsync.helper.Handler.readCSVStructure(Handler.java:242)
	at cloudsync.helper.Handler.init(Handler.java:134)
	at cloudsync.Cloudsync.start(Cloudsync.java:120)
	at cloudsync.Cloudsync.main(Cloudsync.java:160)
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by HolgerHees** [comment]
for some reason, the cache file is not valid. I can add some debug messages on this weekend and then we can check it again.

or you can send me your cache file and I can check what is wrong.

**Comment by giray** [comment]
where is the cache file?

**Comment by HolgerHees** [comment]
it depends on your config file. The default location is the cloudsync directory and the name is

.cloudsync_{backup_name}.config

**Comment by giray** [comment]
found it ... imported in spreadsheet, don't see anything obviously wrong with the file ... also looked with VIM to look if any funny chars where in it ...

The file names are too descriptive, not sure I want to share them ... so If you could provide some debug code, I'd appreciate it ...

thx

**Comment by HolgerHees** [comment]
the nullpointer exceptions shows me that a parent path element was not
found in the cache file.

that means each file entry should have it parent folder in one of the rows
before.

2016-03-31 10:24 GMT+02:00 giray <notifications@github.com>:

**Comment by HolgerHees** [comment]
Can you send me your private emailadresse on http://www.intranet-der-dinge.de/contact

So I can send you a patched version directly.

**Comment by HolgerHees** [comment]
Any news here? I was sending you 2 Emails. The last one 2 weeks ago and I'm still waiting for your answer.
