### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by DigiAngel** [HolgerHees/cloudsync#4]
[2014.12.07 05:44:44] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2014.12.07 05:44:45] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2014.12.07 05:44:45] - INFO - load structure from remote server
[2014.12.07 05:44:47] - INFO - refreshed client token stored in '/opt/cloudsync/.cloudsync.token'
[2014.12.07 05:47:01] - INFO - found 561 folder and 4191 files
[2014.12.07 05:47:01] - INFO - write structure to cache file
[2014.12.07 05:47:04] - FINE - create file 'linuxstuff/ubuntudesktop/VmWare Workstation v.10/VMware-Workstation-Full-10.0.4-2249910.x86_64.bundle.tar.bz2'
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.nio.file.Files.read(Files.java:3099)
        at java.nio.file.Files.readAllBytes(Files.java:3158)
        at cloudsync.connector.LocalFilesystemConnector.getFileBinary(LocalFilesystemConnector.java:586)
        at cloudsync.helper.Handler.getLocalEncryptedBinary(Handler.java:566)
        at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:427)
        at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:178)
        at cloudsync.helper.Handler.backup(Handler.java:468)
        at cloudsync.helper.Handler.backup(Handler.java:528)
        at cloudsync.helper.Handler.backup(Handler.java:528)
        at cloudsync.helper.Handler.backup(Handler.java:528)
        at cloudsync.helper.Handler.backup(Handler.java:425)
        at cloudsync.Cloudsync.start(Cloudsync.java:108)
        at cloudsync.Cloudsync.main(Cloudsync.java:139)

I tried setting the java help on command line via the below:
http://www.firatatagun.com/exception-in-thread-main-java-lang-outofmemoryerror-java-heap-space/

But to no avail.  I can reproduce this everytime.

**Comment by HolgerHees** [comment]
is fixed since v1.0-beta5

**Comment by gelse** [comment]
Just as a reference for anyone who should happen to run into such an issue:

I got this problem again, with a 55m file:
```
ls -alh /home/pi/xxxxxxx
-rw-rw-r-x 1 pi pi 55M Sep 20  2014 /home/pi/xxxxxxx
```
I changed the java call in cloudync.sh:
```
CMD="$JAVA -Xms64m -Xmx256m -cp \"./lib/*\" cloudsync.Cloudsync $*"
```
which seems to work.
(running on a raspberry pi with low RAM, but a huge swap space)

**Comment by HolgerHees** [comment]
currently I"m using a tmp file to encrypt files larger than 128MB. Smaller
files are encrypted in memory. Maybe I should made this 128MB value
configurable.



2015-10-28 11:37 GMT+01:00 Werner Schiller <notifications@github.com>:

**Comment by gelse** [comment]
That would explain, why much larger files were no problem. Thanks.
Another question (i do not want to open a seperate issue for that unless i know on which side the error is):
Now i get a lot of read timeouts, but the encryption seems to work:
```
[2015.10.28 12:02:07] - WARNING - 'Read timed out'item not uploaded - retry 12/12 - wait 5000 ms
[2015.10.28 12:02:12] - WARNING - ioexception: 'Read timed out' - remote upload - retry 1/6
  51% (282304 of 563434 kb) encrypted
```
The source of the files is a fix mounted NAS storage (via samba), but if i read that correctly, the problem is not the read of the original file from NAS (encryption seems to work to 100%) - does "read" in that error mean it could not upload/read the encrypted file or does it mean that the read from gdrive failed?
Additional question: did anyone test with a huge amount of files ? currently it's
```
[2015.10.28 11:25:01] - INFO - found 16 folder and 327 files
```
on my gdrive, but i expect that to increase a LOT.

**Comment by HolgerHees** [comment]
yes it means read from google drive failed currently.

and I run it for my own backup with ~600 folders and ~10000 files with a
total size of 23GB




2015-10-28 12:26 GMT+01:00 Werner Schiller <notifications@github.com>:

**Comment by HolgerHees** [comment]
I added a config option to control this tmp file behavior.

an exanple can be found in cloudsync.config.default


2015-10-28 13:15 GMT+01:00 Holger Hees <holger.hees@gmail.com>:
