### ISSUE TITLE
Very slow on Raspberry Pi 3

### ISSUE THREAD

**Issue by Masek0815** [HolgerHees/cloudsync#40]
Backing up files on a Raspberry Pi 3 is very slow. At 100% CPU for one process it backs up about one 2MB file per minute. Though the Pi 3 is no CPU monster, I know it can do AES256 faster than that.

**Comment by HolgerHees** [comment]
maybe you are OpenJDK. The original Java from Oracle should be faster. Additionally there is no special handling for a raspberry.

http://scruss.com/blog/2013/09/26/faster-java-on-raspberry-pi/

**Comment by Masek0815** [comment]
Thank you. Though I had installed Oracle JDK 8 to compile, it was still running on the OpenJDK JVM.  Instead of 117s per file we are now at 13s. That is nearly one order of magnitude. Still slow though, but a backup is no race horse ;-).

**Comment by Masek0815** [comment]
Short information:
a) One should refer to the installation of the "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files" in the requirements.
b) Raspberry Pi 3 needs a manual increase of the the heap size, otherwise it will crash on files around 70-90MB (though working without problems with even larger files):

[2017.01.22 00:15:15] - FINE - create file '**********************'
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.partialFlush(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.writePartial(Unknown Source)
        at org.bouncycastle.bcpg.BCPGOutputStream.write(Unknown Source)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.write(Unknown Source)
        at cloudsync.helper.Crypt._encryptData(Crypt.java:270)
        at cloudsync.helper.Crypt.encryptedBinary(Crypt.java:177)
        at cloudsync.helper.Handler.getLocalProcessedBinary(Handler.java:646)
        at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:516)
        at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:216)
        at cloudsync.helper.Handler.backup(Handler.java:519)
        at cloudsync.helper.Handler.backup(Handler.java:587)
        at cloudsync.helper.Handler.backup(Handler.java:587)
        at cloudsync.helper.Handler.backup(Handler.java:472)
        at cloudsync.Cloudsync.start(Cloudsync.java:132)
        at cloudsync.Cloudsync.main(Cloudsync.java:160)
