### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException in v1.0-beta5

### ISSUE THREAD

**Issue by SVolkert** [HolgerHees/cloudsync#6]
Hi Holger,
today i tried to backup my files...

```bash
$ /opt/java/cloudsync/cloudsync.sh --backup /home/stephan/dissertation --name promotionBackup --exclude .git/
/opt/java/cloudsync/cloudsync.sh: 10: /opt/java/cloudsync/cloudsync.sh: cannot open 1.7: No such file
/opt/java/cloudsync/cloudsync.sh: 10: /opt/java/cloudsync/cloudsync.sh: [[: not found
[2015.01.04 12:00:11] - FINEST - use exclude pattern: [^.git/$]
[2015.01.04 12:00:11] - INFO - load structure from remote server
[2015.01.04 12:00:12] - INFO - refreshed client token stored in '/opt/java/cloudsync/.cloudsync.token'
[2015.01.04 12:00:14] - FINE - create file 'DeckblattUmfrage.tex.backup'
[2015.01.04 12:00:15] - FINE - create file 'flussdiagramm.tex'
[2015.01.04 12:00:16] - FINE - create folder 'Auswertung'
Exception in thread "main" java.lang.NullPointerException
        at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
        at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
        at com.google.api.client.http.InputStreamContent.<init>(InputStreamContent.java:68)
        at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:183)
        at cloudsync.helper.Handler.backup(Handler.java:471)                                                                                                                        
        at cloudsync.helper.Handler.backup(Handler.java:428)                                                                                                                        
        at cloudsync.Cloudsync.start(Cloudsync.java:108)                                                                                                                            
        at cloudsync.Cloudsync.main(Cloudsync.java:139) 
```

Stephan

PS: no error messages in v1.0-beta4

**Comment by HolgerHees** [comment]
is fixed with v1.0-beta6
