### ISSUE TITLE
java.nio.file.FileSystemException: Too many open files

### ISSUE THREAD

**Issue by giray** [HolgerHees/cloudsync#9]
Backing up a 35Gig directory with 24625 files resulted in the following error.  

Running: cloudsync-v1.0-beta6

[2015.02.24 13:41:32] - FINE - create file 'MZ3/__actualTitle/gui_c/index/btn_next.png'
[2015.02.24 13:41:33] - FINE - create file 'MZ3/__actualTitle/gui_c/password.asul'
[2015.02.24 13:41:33] - INFO - error: Can't read data of '/home/giray/Documents/MZ3/__actualTitle/gui_c/password.asul'

cloudsync.exceptions.CloudsyncException: Can't read data of '/home/giray/Documents/MZ3/__actualTitle/gui_c/password.asul'
	at cloudsync.connector.LocalFilesystemConnector.getFileBinary(LocalFilesystemConnector.java:648)
	at cloudsync.helper.Handler.getLocalEncryptedBinary(Handler.java:570)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareDriveItem(RemoteGoogleDriveConnector.java:428)
	at cloudsync.connector.RemoteGoogleDriveConnector.upload(RemoteGoogleDriveConnector.java:179)
	at cloudsync.helper.Handler.backup(Handler.java:471)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:531)
	at cloudsync.helper.Handler.backup(Handler.java:428)
	at cloudsync.Cloudsync.start(Cloudsync.java:108)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)
Caused by: java.nio.file.FileSystemException: /home/giray/Documents/MZ3/__actualTitle/gui_c/password.asul: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at cloudsync.connector.LocalFilesystemConnector.getFileBinary(LocalFilesystemConnector.java:643)

Running it afterwards causes

giray@laptop:~/bin/cloudsync$ ./cloudsync.sh --name My.Documents" --backup /home/giray/Documents/
[2015.02.24 13:44:52] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.02.24 13:44:52] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.02.24 13:44:52] - INFO - load structure from remote server
[2015.02.24 13:44:53] - INFO - refreshed client token stored in '/home/giray/bin/cloudsync/.cloudsync.token'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareBackupItem(RemoteGoogleDriveConnector.java:466)
	at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:339)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:231)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:224)
	at cloudsync.helper.Handler.init(Handler.java:125)
	at cloudsync.Cloudsync.start(Cloudsync.java:104)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)

**Comment by HolgerHees** [comment]
i will take a look at this problem today evening.

are you able to build and test my fix directly from github sources?

**Comment by giray** [comment]
Long time no java :)  but if you give me a one-liner on howto build...

is
   mvn package

sufficient?

gd

**Comment by HolgerHees** [comment]
you can send me your email address via the contact form on

http://www.intranet-of-things.com/contact

then I will send you a pre beta7 ~ at 10pm :-)

**Comment by HolgerHees** [comment]
mvn package is sufficient

**Comment by giray** [comment]
you have mail... :)

**Comment by HolgerHees** [comment]
ok, no need for a seperate mail. I have prepeared and uploaded the "final" beta7. :-)

if you overwrite your current cloudsync folder with the new one, take care to remove the old lib/cloudsync-v1.0-beta6.jar

**Comment by HolgerHees** [comment]
I found more places inside the code which are responsible for the "Too many open files" exception. Currently I'm working on an additional update "beta8" which will be released tomorrow. I verified this solution with "lsof -n" and it looks good. But you have to be patient until tomorrow :-)

**Comment by giray** [comment]
Hi ..  

   just getting around for testing .. and I get the following

[2015.03.02 16:22:59] - INFO - client token stored in '/home/giray/bin/cloudsync/.cloudsync.token'
[2015.03.02 16:22:59] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.03.02 16:23:00] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.03.02 16:23:00] - INFO - load structure from remote server
[2015.03.02 16:23:00] - INFO - refreshed client token stored in '/home/giray/bin/cloudsync/.cloudsync.token'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareBackupItem(RemoteGoogleDriveConnector.java:466)
	at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:339)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:231)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:224)
	at cloudsync.helper.Handler.init(Handler.java:125)
	at cloudsync.Cloudsync.start(Cloudsync.java:104)
	at cloudsync.Cloudsync.main(Cloudsync.java:139)
giray@wasp:~/bin/cloudsync$ ./cloudsync.sh --name "Wasp.Giray.bin" --clean /home/giray/bin/
[2015.03.02 16:23:56] - FINEST - use exclude pattern: [^.*\.git/.*$] | [$.*\.svn/.*$]
[2015.03.02 16:23:56] - WARNING - Found an inconsistent cache file state. Possibly previous job has crashed or duplicate files was detected. Force a cache file rebuild.
[2015.03.02 16:23:56] - INFO - load structure from remote server
[2015.03.02 16:23:56] - INFO - refreshed client token stored in '/home/giray/bin/cloudsync/.cloudsync.token'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at cloudsync.connector.RemoteGoogleDriveConnector._prepareBackupItem(RemoteGoogleDriveConnector.java:466)
	at cloudsync.connector.RemoteGoogleDriveConnector.readFolder(RemoteGoogleDriveConnector.java:339)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:231)
	at cloudsync.helper.Handler.readRemoteStructure(Handler.java:224)
	at cloudsync.helper.Handler.init(Handler.java:125)
	at cloudsync.Cloudsync.start(Cloudsync.java:104)
	at cloudsync.Cloudsync.mai
